// Shared sample fallback profiles for Asan Nikah (shown when the database is empty or unreachable)

export interface SampleProfile {
  id: string;
  userId: string;
  email: string;
  fullName: string;
  gender: 'Male' | 'Female';
  dateOfBirth: string; // ISO string YYYY-MM-DD
  maritalStatus: 'Single' | 'Divorced' | 'Widowed';
  phoneNumber: string;
  city: string;
  locality: string;
  state: string;
  country: string;
  education: string;
  occupation: string;
  annualIncomeRange: string;
  familyInfo: string;
  bio: string;
  themeColor: string;
  verificationStatus: 'PENDING' | 'APPROVED' | 'REJECTED' | 'NEEDS_FOLLOW_UP';
  profileCompletionStatus: 'COMPLETE' | 'INCOMPLETE';
  hasPaid: boolean;
  category: 'good_profile' | 'second_marriage' | 'high_profile' | 'normal';
  packageType?: 'monthly_membership' | 'good_profile_package' | 'second_marriage_package' | 'high_profile_package';
  packagePrice?: number;
  regDate: string; // ISO string YYYY-MM-DD

  // Identity
  maslak: string;
  fiqh: string;
  biradari: string;
}

export const sampleProfiles: SampleProfile[] = [
  // ==================== 1. GOOD PROFILES PACKAGE (₹500) ====================
  // Criteria: Single, First Marriage, decent job (no doctor/engineer/business/professional), income < 10 LPA
  {
    id: '60d5ecb86f67a213e4b7b263',
    userId: '60d5ecb86f67a213e4b7b253',
    email: 'sample_adnan_siddiqui@example.com',
    fullName: 'Adnan Siddiqui',
    gender: 'Male',
    dateOfBirth: '1997-03-05',
    maritalStatus: 'Single',
    phoneNumber: '+919999900101',
    city: 'Delhi',
    locality: 'Karol Bagh',
    state: 'Delhi',
    country: 'India',
    education: 'MBA in Logistics',
    occupation: 'Export Firm Manager',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Well-settled family in Central Delhi. Father is a retired exporter. Mother is a housewife. One elder brother.',
    bio: 'Down-to-earth and family-oriented. Working in logistics management. Looking for a pious, educated life partner who balances family values and modern life.',
    themeColor: 'hsl(42, 58%, 53%)', // Gold
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-05-20',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    id: '60d5ecb86f67a213e4b7b301',
    userId: '60d5ecb86f67a213e4b7b311',
    email: 'sample_zainab_ahmed@example.com',
    fullName: 'Zainab Ahmed',
    gender: 'Female',
    dateOfBirth: '2002-02-14',
    maritalStatus: 'Single',
    phoneNumber: '+919999900102',
    city: 'Noida',
    locality: 'Sector 62',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.A. English Literature',
    occupation: 'Content Writer',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Father is a retired administrative officer. Mother is a homemaker. One elder sister, married.',
    bio: 'Avid reader and creative writer. Strive to maintain a balance of Deen and Dunya. Looking for a responsible, gentle companion who values simple living.',
    themeColor: 'hsl(200, 45%, 18%)', // Navy
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-01',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b302',
    userId: '60d5ecb86f67a213e4b7b312',
    email: 'sample_yasmin_alvi@example.com',
    fullName: 'Yasmin Alvi',
    gender: 'Female',
    dateOfBirth: '1998-12-03',
    maritalStatus: 'Single',
    phoneNumber: '+919999900103',
    city: 'Aligarh',
    locality: 'AMU Campus',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'M.Sc Chemistry',
    occupation: 'Lecturer',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Academic background. Father is an AMU professor. Mother is a housewife. Two brothers, both settled.',
    bio: 'Passionate educator who loves gardening and literature. Seeking a well-educated, respectful partner who holds high moral values and respect for elders.',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-07',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Alvi',
  },
  {
    id: '60d5ecb86f67a213e4b7b303',
    userId: '60d5ecb86f67a213e4b7b313',
    email: 'sample_sameer_deshmukh@example.com',
    fullName: 'Sameer Deshmukh',
    gender: 'Male',
    dateOfBirth: '1998-08-22',
    maritalStatus: 'Single',
    phoneNumber: '+919999900104',
    city: 'Bhopal',
    locality: 'Arera Colony',
    state: 'Madhya Pradesh',
    country: 'India',
    education: 'B.Sc Economics',
    occupation: 'Tax Consultant',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Respectable service-class family. Father is a state government employee. Mother is a teacher. One younger sister.',
    bio: 'Sincere, disciplined, and family-oriented. Working as an independent tax advisor. Seeking an educated girl with traditional Islamic ethics.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-08',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    id: '60d5ecb86f67a213e4b7b304',
    userId: '60d5ecb86f67a213e4b7b314',
    email: 'sample_tarannum_jehan@example.com',
    fullName: 'Tarannum Jehan',
    gender: 'Female',
    dateOfBirth: '2000-10-29',
    maritalStatus: 'Single',
    phoneNumber: '+919999900105',
    city: 'Ghaziabad',
    locality: 'Indirapuram',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.Ed, B.Sc',
    occupation: 'School Teacher',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Middle-class family. Father is a bank accountant. Mother is a homemaker. Two younger sisters.',
    bio: 'Warm and caring primary school teacher. I love children, crafts, and baking. Seeking a gentle and responsible life partner who values education and simple living.',
    themeColor: 'hsl(200, 45%, 18%)', // Navy
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-09',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b305',
    userId: '60d5ecb86f67a213e4b7b315',
    email: 'sample_raza_murad@example.com',
    fullName: 'Raza Murad',
    gender: 'Male',
    dateOfBirth: '2001-02-05',
    maritalStatus: 'Single',
    phoneNumber: '+919999900106',
    city: 'Noida',
    locality: 'Sector 15',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.Sc Computer Science',
    occupation: 'QA Analyst',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father runs a retail electrical store. Mother is a housewife. One younger brother.',
    bio: 'Working as a QA analyst in Noida. Love fitness, reading, and learning new things. Looking for a positive, cheerful girl who values family values and Deen.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-10',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    id: '60d5ecb86f67a213e4b7b306',
    userId: '60d5ecb86f67a213e4b7b316',
    email: 'sample_farah_sheikh@example.com',
    fullName: 'Farah Sheikh',
    gender: 'Female',
    dateOfBirth: '1999-05-15',
    maritalStatus: 'Single',
    phoneNumber: '+919999900107',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'MBA in HR',
    occupation: 'HR Recruiter',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Respectable Lucknow family. Father is a senior lawyer. Mother is a housewife. One brother.',
    bio: 'Dynamic yet humble. Striving to practice Islamic principles in daily life. Looking for a supportive companion who is well-settled and respectful.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-11',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b307',
    userId: '60d5ecb86f67a213e4b7b317',
    email: 'sample_arshad_warsi@example.com',
    fullName: 'Arshad Warsi',
    gender: 'Male',
    dateOfBirth: '1999-11-25',
    maritalStatus: 'Single',
    phoneNumber: '+919999900108',
    city: 'Jaipur',
    locality: 'Johri Bazar',
    state: 'Rajasthan',
    country: 'India',
    education: 'B.Arch',
    occupation: 'Architectural Consultant',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Artisan family. Father is a jewelry designer. Mother is a homemaker. Two brothers.',
    bio: 'Working as an architectural designer in Jaipur. I value honesty, simple living, and prayers. Looking for an educated, modest girl with traditional values.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-12',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Mughal',
  },
  {
    id: '60d5ecb86f67a213e4b7b308',
    userId: '60d5ecb86f67a213e4b7b318',
    email: 'sample_sobia_qureshi@example.com',
    fullName: 'Sobia Qureshi',
    gender: 'Female',
    dateOfBirth: '2001-09-12',
    maritalStatus: 'Single',
    phoneNumber: '+919999900109',
    city: 'Delhi',
    locality: 'Daryaganj',
    state: 'Delhi',
    country: 'India',
    education: 'B.Des Fashion Design',
    occupation: 'Fashion Consultant',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Upper middle-class. Father runs a pharmaceutical trading firm. Mother is a homemaker. One brother.',
    bio: 'Creative, optimistic, and deeply religious. Love art, travel, and cooking. Seeking a practicing Sunni gentleman with good education and high values.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    id: '60d5ecb86f67a213e4b7b309',
    userId: '60d5ecb86f67a213e4b7b319',
    email: 'sample_imran_mansuri@example.com',
    fullName: 'Imran Mansuri',
    gender: 'Male',
    dateOfBirth: '1996-06-24',
    maritalStatus: 'Single',
    phoneNumber: '+919999900110',
    city: 'Mumbai',
    locality: 'Kurla',
    state: 'Maharashtra',
    country: 'India',
    education: 'M.Com',
    occupation: 'Operations Supervisor',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father runs a general retail store. Mother is a homemaker. Two younger sisters, studying.',
    bio: 'Responsible, soft-spoken, and helpful. Working as an operations supervisor in Mumbai. Striving to balance Deen and Dunya. Looking for a modest bride.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 500,
    category: 'good_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Mansuri',
  },

  // ==================== 2. SECOND MARRIAGE PACKAGE (₹600) ====================
  // Criteria: Divorced/Widowed, mix male/female, under 10LPA income, occupations avoiding high profile keywords
  {
    id: '60d5ecb86f67a213e4b7b262',
    userId: '60d5ecb86f67a213e4b7b252',
    email: 'sample_aisha_rahman@example.com',
    fullName: 'Aisha Rahman',
    gender: 'Female',
    dateOfBirth: '1995-09-20',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900111',
    city: 'Bengaluru',
    locality: 'Indiranagar',
    state: 'Karnataka',
    country: 'India',
    education: 'M.Tech Computer Science',
    occupation: 'Senior Web Developer',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Educated family. Father is an administrator, mother is a teacher. Two sisters, both happily married.',
    bio: 'Simple and pious. software professional. Divorced after a short marriage (no children). Seeking a clean-hearted, responsible partner for a fresh start.',
    themeColor: 'hsl(175, 45%, 20%)', // Teal
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-05-15',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    id: '60d5ecb86f67a213e4b7b267',
    userId: '60d5ecb86f67a213e4b7b257',
    email: 'sample_farhan_syed@example.com',
    fullName: 'Farhan Syed',
    gender: 'Male',
    dateOfBirth: '1991-04-10',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900112',
    city: 'Mumbai',
    locality: 'Andheri West',
    state: 'Maharashtra',
    country: 'India',
    education: 'B.Sc IT',
    occupation: 'Technical Lead',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father is a retired banking officer. Mother is a homemaker. No siblings. Living in own apartment.',
    bio: 'Seeking a second chance at marriage based on mutual respect and clarity. Divorced. Striving to practice daily prayers. Looking for an understanding partner.',
    themeColor: 'hsl(42, 58%, 53%)', // Gold
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-04-20',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    id: '60d5ecb86f67a213e4b7b268',
    userId: '60d5ecb86f67a213e4b7b258',
    email: 'sample_mariam_fatimah@example.com',
    fullName: 'Mariam Fatimah',
    gender: 'Female',
    dateOfBirth: '1992-06-18',
    maritalStatus: 'Widowed',
    phoneNumber: '+919999900113',
    city: 'Jaipur',
    locality: 'C-Scheme',
    state: 'Rajasthan',
    country: 'India',
    education: 'M.Com',
    occupation: 'Accountant',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father is a general merchant. Mother is a teacher. One younger brother.',
    bio: 'Pious, independent widow. Mother of a 4-year-old daughter. Looking for a compassionate partner who can be a loving husband and a caring father figure.',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-05-01',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Pathan',
  },
  {
    id: '60d5ecb86f67a213e4b7b321',
    userId: '60d5ecb86f67a213e4b7b331',
    email: 'sample_shabana_bano@example.com',
    fullName: 'Shabana Bano',
    gender: 'Female',
    dateOfBirth: '1986-03-14',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900114',
    city: 'Lucknow',
    locality: 'Aliganj',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.A. Urdu',
    occupation: 'Senior Homemaker',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Traditional family. Father is retired. Three brothers, all married and settled.',
    bio: 'Caring, soft-spoken, and domestic. Divorced. Mother of a 10-year-old son who lives with me. Seeking a respectful and mature partner to rebuild a peaceful home.',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-05-10',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    id: '60d5ecb86f67a213e4b7b322',
    userId: '60d5ecb86f67a213e4b7b332',
    email: 'sample_imran_malik@example.com',
    fullName: 'Imran Malik',
    gender: 'Male',
    dateOfBirth: '1984-09-30',
    maritalStatus: 'Widowed',
    phoneNumber: '+919999900115',
    city: 'Ghaziabad',
    locality: 'Raj Nagar',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.Sc Chemistry',
    occupation: 'Shop Proprietor',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Middle-class family. Living with two kids (ages 12 and 8). Father has retired.',
    bio: 'Widower seeking a kind, nurturing companion to rebuild a warm home. I run a retail electrical store. Value family values, piety, and mutual support.',
    themeColor: 'hsl(42, 58%, 53%)', // Gold
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-05-12',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    id: '60d5ecb86f67a213e4b7b323',
    userId: '60d5ecb86f67a213e4b7b333',
    email: 'sample_hina_shaheen@example.com',
    fullName: 'Hina Shaheen',
    gender: 'Female',
    dateOfBirth: '1995-11-15',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900116',
    city: 'Bhopal',
    locality: 'Jahangirabad',
    state: 'Madhya Pradesh',
    country: 'India',
    education: 'M.A. Literature',
    occupation: 'Creative Writer',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Father is a retired administrative clerk. Mother is a housewife. One sister, married.',
    bio: 'Divorced. Quiet and creative. Working as a content editor and writer. Looking for a partner who is honest, understands mutual respect, and practices Deen.',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-06-12',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Pathan',
  },
  {
    id: '60d5ecb86f67a213e4b7b324',
    userId: '60d5ecb86f67a213e4b7b334',
    email: 'sample_javed_jaffrey@example.com',
    fullName: 'Javed Jaffrey',
    gender: 'Male',
    dateOfBirth: '1995-01-15',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900117',
    city: 'Mumbai',
    locality: 'Colaba',
    state: 'Maharashtra',
    country: 'India',
    education: 'MBA in Marketing',
    occupation: 'Marketing Manager',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father is a retired merchant navy officer. Mother is a homemaker. One brother.',
    bio: 'Seeking a second marriage. Divorced. Modern outlook but grounded in values. Loves fitness, reading, and travel. Seeking a mature, understanding life partner.',
    themeColor: 'hsl(42, 58%, 53%)', // Gold
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b325',
    userId: '60d5ecb86f67a213e4b7b335',
    email: 'sample_rehana_parveen@example.com',
    fullName: 'Rehana Parveen',
    gender: 'Female',
    dateOfBirth: '1996-04-20',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900118',
    city: 'Delhi',
    locality: 'Zakir Nagar',
    state: 'Delhi',
    country: 'India',
    education: 'B.A. Education',
    occupation: 'Primary School Teacher',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Simple, respectable family in South Delhi. Father runs a book store. Two brothers.',
    bio: 'Soft-hearted and caring. Divorced. Working as a primary school teacher in a local institution. Looking for a simple, sincere, and family-oriented partner.',
    themeColor: 'hsl(200, 45%, 18%)', // Navy
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-06-13',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b326',
    userId: '60d5ecb86f67a213e4b7b336',
    email: 'sample_salman_baig@example.com',
    fullName: 'Salman Baig',
    gender: 'Male',
    dateOfBirth: '1990-02-15',
    maritalStatus: 'Divorced',
    phoneNumber: '+919999900119',
    city: 'Lucknow',
    locality: 'Aminabad',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'High School',
    occupation: 'Retail Merchant',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Middle-class family in old Lucknow. Parents live with me. One sister.',
    bio: 'Sincere, down-to-earth shopkeeper. Divorced. Seeking a simple, pious girl who values family attachment and religious traditions.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Mughal',
  },
  {
    id: '60d5ecb86f67a213e4b7b327',
    userId: '60d5ecb86f67a213e4b7b337',
    email: 'sample_nisar_sheikh@example.com',
    fullName: 'Nisar Sheikh',
    gender: 'Male',
    dateOfBirth: '1988-06-12',
    maritalStatus: 'Widowed',
    phoneNumber: '+919999900120',
    city: 'Hyderabad',
    locality: 'Tolichowki',
    state: 'Telangana',
    country: 'India',
    education: 'B.Com',
    occupation: 'Senior Clerk',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Respectable family from Hyderabad. No children. Living with elderly parents.',
    bio: 'Widower. Quiet, disciplined, and practicing Sunni. Working as a senior office clerk. Seeking an educated, caring woman for a long-term Nikah relationship.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 600,
    category: 'second_marriage',
    regDate: '2026-06-14',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },

  // ==================== 3. HIGH PROFILE PACKAGE (₹800) ====================
  // Criteria: Single, First Marriage, Doctor/Engineer/Business/Corporate Professional, Income ₹10 LPA+
  {
    id: '60d5ecb86f67a213e4b7b261',
    userId: '60d5ecb86f67a213e4b7b251',
    email: 'sample_sarah_khan@example.com',
    fullName: 'Dr. Sarah Khan',
    gender: 'Female',
    dateOfBirth: '1999-05-12',
    maritalStatus: 'Single',
    phoneNumber: '+919999900121',
    city: 'Mumbai',
    locality: 'Bandra West',
    state: 'Maharashtra',
    country: 'India',
    education: 'MD, MBBS',
    occupation: 'Pediatrician (Doctor)',
    annualIncomeRange: '₹12 LPA - ₹15 LPA',
    familyInfo: 'Highly educated family. Father is a retired university professor. Mother is a homemaker. One younger brother, studying in the US.',
    bio: 'Pious, compassionate, and career-oriented. Striving to manage professional growth and Islamic values. Looking for a highly educated partner (Doctor/Engineer/MBA).',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-04-10',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    id: '60d5ecb86f67a213e4b7b278',
    userId: '60d5ecb86f67a213e4b7b288',
    email: 'sample_nida_fatma@example.com',
    fullName: 'Nida Fatma',
    gender: 'Female',
    dateOfBirth: '1997-09-09',
    maritalStatus: 'Single',
    phoneNumber: '+919999900122',
    city: 'Hyderabad',
    locality: 'Jubilee Hills',
    state: 'Telangana',
    country: 'India',
    education: 'MBBS, MD',
    occupation: 'Resident Gynecologist (Doctor)',
    annualIncomeRange: '₹10 LPA - ₹15 LPA',
    familyInfo: 'Elite Hyderabad family. Father is an orthopedic surgeon. Mother is a senior doctor. One brother (tech engineer).',
    bio: 'Currently doing postgraduate residency. Balanced, career-oriented yet values traditional family life. Seeking a professional partner with good character.',
    themeColor: 'hsl(345, 65%, 28%)', // Crimson
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-13',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    id: '60d5ecb86f67a213e4b7b297',
    userId: '60d5ecb86f67a213e4b7b298',
    email: 'sample_mansoor_ali@example.com',
    fullName: 'Mansoor Ali',
    gender: 'Male',
    dateOfBirth: '1997-09-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900123',
    city: 'Bengaluru',
    locality: 'Whitefield',
    state: 'Karnataka',
    country: 'India',
    education: 'M.S. Data Science',
    occupation: 'Lead AI Professional',
    annualIncomeRange: '₹15 LPA - ₹25 LPA',
    familyInfo: 'Intellectual family. Father is a retired corporate scientist. Mother is a private school principal. One brother.',
    bio: 'Data scientist in Bengaluru. Practice Islamic values and balance with corporate lifestyle. Looking for a partner who is educated, positive, and religious.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-12',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    id: '60d5ecb86f67a213e4b7b341',
    userId: '60d5ecb86f67a213e4b7b351',
    email: 'sample_tariq_anwar@example.com',
    fullName: 'Tariq Anwar',
    gender: 'Male',
    dateOfBirth: '1994-06-15',
    maritalStatus: 'Single',
    phoneNumber: '+919999900124',
    city: 'Pune',
    locality: 'Deccan Gymkhana',
    state: 'Maharashtra',
    country: 'India',
    education: 'B.Tech in Computer Science',
    occupation: 'Senior Software Engineer',
    annualIncomeRange: '₹15 LPA - ₹25 LPA',
    familyInfo: 'Father is an executive engineer. Mother is a housewife. One sister, married.',
    bio: 'Working as a Senior Developer in Pune. Sincere, loving, and focused on prayers. Seeking an educated, modest, and family-oriented life partner.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    id: '60d5ecb86f67a213e4b7b342',
    userId: '60d5ecb86f67a213e4b7b352',
    email: 'sample_khalid_masood@example.com',
    fullName: 'Khalid Masood',
    gender: 'Male',
    dateOfBirth: '1992-11-18',
    maritalStatus: 'Single',
    phoneNumber: '+919999900125',
    city: 'Delhi',
    locality: 'Connaught Place',
    state: 'Delhi',
    country: 'India',
    education: 'MBA from FMS Delhi',
    occupation: 'Premium Business Owner',
    annualIncomeRange: 'Above ₹25 LPA',
    familyInfo: 'Premium business family in Delhi. Owns chain of medical supplies. One brother, one sister.',
    bio: 'Managing family business and startup. Ambitious, down-to-earth, and practicing. Looking for a modern, well-educated, and religious life partner.',
    themeColor: 'hsl(42, 58%, 53%)', // Gold
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b343',
    userId: '60d5ecb86f67a213e4b7b353',
    email: 'sample_faisal_qureshi@example.com',
    fullName: 'Faisal Qureshi',
    gender: 'Male',
    dateOfBirth: '1994-07-25',
    maritalStatus: 'Single',
    phoneNumber: '+919999900126',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'MD Medicine',
    occupation: 'Consultant Cardiologist (Doctor)',
    annualIncomeRange: '₹15 LPA - ₹25 LPA',
    familyInfo: 'Respected Lucknow family. Father runs a pharmaceutical trading firm. Mother is a housewife. One sister.',
    bio: 'Practicing cardiologist. Calm, dedicated, and family-oriented. Striving for a pure lifestyle. Seeking a highly educated girl with a warm heart.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-05',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    id: '60d5ecb86f67a213e4b7b344',
    userId: '60d5ecb86f67a213e4b7b354',
    email: 'sample_asma_siddiqui@example.com',
    fullName: 'Asma Siddiqui',
    gender: 'Female',
    dateOfBirth: '1998-02-10',
    maritalStatus: 'Single',
    phoneNumber: '+919999900127',
    city: 'Delhi',
    locality: 'Okhla',
    state: 'Delhi',
    country: 'India',
    education: 'Chartered Accountant (CA)',
    occupation: 'Chartered Accountant (Professional)',
    annualIncomeRange: '₹12 LPA - ₹15 LPA',
    familyInfo: 'Middle-class. Father is an accountant in Delhi. Mother is a homemaker. One younger brother, CA student.',
    bio: 'Working as a Senior Auditor. Independent, religious, and soft-spoken. Seeking a practicing professional with high ethics and clean habits.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    id: '60d5ecb86f67a213e4b7b345',
    userId: '60d5ecb86f67a213e4b7b355',
    email: 'sample_riaz_ahmed@example.com',
    fullName: 'Riaz Ahmed',
    gender: 'Male',
    dateOfBirth: '1993-03-28',
    maritalStatus: 'Single',
    phoneNumber: '+919999900128',
    city: 'Hyderabad',
    locality: 'Banjara Hills',
    state: 'Telangana',
    country: 'India',
    education: 'LL.M from NLSIU Bangalore',
    occupation: 'Corporate Lawyer (Professional)',
    annualIncomeRange: '₹15 LPA - ₹25 LPA',
    familyInfo: 'Father is a retired judge. Mother is a lecturer. Two sisters, married.',
    bio: 'Corporate legal counsel in Hyderabad. Religious, values truth and family. Seeking an educated, pious girl who can manage home and values with grace.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    id: '60d5ecb86f67a213e4b7b346',
    userId: '60d5ecb86f67a213e4b7b356',
    email: 'sample_zainab_malik@example.com',
    fullName: 'Zainab Malik',
    gender: 'Female',
    dateOfBirth: '1996-08-15',
    maritalStatus: 'Single',
    phoneNumber: '+919999900129',
    city: 'Mumbai',
    locality: 'Juhu',
    state: 'Maharashtra',
    country: 'India',
    education: 'MBA from NMIMS Mumbai',
    occupation: 'Management Consultant (Professional)',
    annualIncomeRange: '₹12 LPA - ₹15 LPA',
    familyInfo: 'Father is a private company director. Mother runs an Islamic charity school. One sister.',
    bio: 'Working in advisory consulting. Pious, modest, and travel lover. Seeking a well-settled professional Sunni groom with good education and character.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    id: '60d5ecb86f67a213e4b7b347',
    userId: '60d5ecb86f67a213e4b7b357',
    email: 'sample_kamran_surgeon@example.com',
    fullName: 'Dr. Kamran Khan',
    gender: 'Male',
    dateOfBirth: '1991-12-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900130',
    city: 'Bhopal',
    locality: 'Shahpura',
    state: 'Madhya Pradesh',
    country: 'India',
    education: 'MS General Surgery',
    occupation: 'Senior Surgeon (Doctor)',
    annualIncomeRange: 'Above ₹25 LPA',
    familyInfo: 'Doctor family. Father is a retired medical director. Mother is a gynecologist. Two brothers.',
    bio: 'Working as a Consultant Surgeon in Bhopal. Grounded, focused on Deen, and loves humanitarian work. Seeking an educated, pious Muslim girl.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 800,
    category: 'high_profile',
    regDate: '2026-06-14',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },

  // ==================== 4. STANDARD/MONTHLY MEMBERSHIP PROFILES (₹300) ====================
  // Criteria: Single, First Marriage, normal job (no doctor/engineer/business/professional), income < 10 LPA
  {
    id: '60d5ecb86f67a213e4b7b361',
    userId: '60d5ecb86f67a213e4b7b371',
    email: 'sample_bilal_chishti@example.com',
    fullName: 'Bilal Chishti',
    gender: 'Male',
    dateOfBirth: '2000-06-12',
    maritalStatus: 'Single',
    phoneNumber: '+919999900131',
    city: 'Delhi',
    locality: 'Okhla',
    state: 'Delhi',
    country: 'India',
    education: 'M.Tech',
    occupation: 'Research Scholar',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Noble middle-class family. Father is retired. Mother is a housewife. One sister.',
    bio: 'Academic researcher, quiet and thoughtful. Deeply value honesty and prayers. Looking for an educated partner who values simple living.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    id: '60d5ecb86f67a213e4b7b362',
    userId: '60d5ecb86f67a213e4b7b372',
    email: 'sample_sana_parveen@example.com',
    fullName: 'Sana Parveen',
    gender: 'Female',
    dateOfBirth: '2001-03-28',
    maritalStatus: 'Single',
    phoneNumber: '+919999900132',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.FA in Applied Arts',
    occupation: 'Graphic Artist',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Artist family. Father has printing shop. Mother is a homemaker. One sister.',
    bio: 'Creative web illustrator and graphic artist. Striving to follow Deen and live peacefully. Seeking a simple and helpful partner with sound education.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    id: '60d5ecb86f67a213e4b7b363',
    userId: '60d5ecb86f67a213e4b7b373',
    email: 'sample_kamran_ansari@example.com',
    fullName: 'Kamran Ansari',
    gender: 'Male',
    dateOfBirth: '1998-12-01',
    maritalStatus: 'Single',
    phoneNumber: '+919999900133',
    city: 'Bhopal',
    locality: 'Shahpura',
    state: 'Madhya Pradesh',
    country: 'India',
    education: 'B.Sc in Biotechnology',
    occupation: 'Lab Technician',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Respectable service family. Father is a security supervisor. Mother is a homemaker.',
    bio: 'Working as a lab technician in Bhopal. Simple, honest, and helpful. Looking for a modest, domestic girl who is family-oriented.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    id: '60d5ecb86f67a213e4b7b364',
    userId: '60d5ecb86f67a213e4b7b374',
    email: 'sample_sameera_begum@example.com',
    fullName: 'Sameera Begum',
    gender: 'Female',
    dateOfBirth: '2000-04-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900134',
    city: 'Hyderabad',
    locality: 'Charminar',
    state: 'Telangana',
    country: 'India',
    education: 'B.Ed, B.A.',
    occupation: 'Primary Teacher',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Middle-class family from old city Hyderabad. Father is retired. Mother is a housewife. One sister.',
    bio: 'Simple primary school teacher. I value prayers, modesty, and family. Seeking an honest and supportive life partner who resides in Hyderabad.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b365',
    userId: '60d5ecb86f67a213e4b7b375',
    email: 'sample_farooq_sheikh@example.com',
    fullName: 'Farooq Sheikh',
    gender: 'Male',
    dateOfBirth: '1996-07-12',
    maritalStatus: 'Single',
    phoneNumber: '+919999900135',
    city: 'Mumbai',
    locality: 'Kurla',
    state: 'Maharashtra',
    country: 'India',
    education: 'B.Com',
    occupation: 'Customer Executive',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Middle-class Kurla family. Father runs a tailoring shop. Mother is a homemaker. One younger brother.',
    bio: 'Working in customer operations. Sincere, hard-working, and focused on Deen. Seeking a helpful, domestic girl who is family-oriented and respectful.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b366',
    userId: '60d5ecb86f67a213e4b7b376',
    email: 'sample_humaira_qureshi@example.com',
    fullName: 'Humaira Qureshi',
    gender: 'Female',
    dateOfBirth: '2001-06-23',
    maritalStatus: 'Single',
    phoneNumber: '+919999900136',
    city: 'Delhi',
    locality: 'Zakir Nagar',
    state: 'Delhi',
    country: 'India',
    education: 'B.Des in Fashion',
    occupation: 'Fashion Stylist',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Father runs a small garment manufacturing unit. Mother is a homemaker. One brother.',
    bio: 'Stylist in Delhi. Creative, cheerful, and modest. Values traditional boundaries and prayers. Seeking a supportive Sunni gentleman.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    id: '60d5ecb86f67a213e4b7b367',
    userId: '60d5ecb86f67a213e4b7b377',
    email: 'sample_majid_malik@example.com',
    fullName: 'Majid Malik',
    gender: 'Male',
    dateOfBirth: '1997-09-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900137',
    city: 'Bengaluru',
    locality: 'Indiranagar',
    state: 'Karnataka',
    country: 'India',
    education: 'B.BA',
    occupation: 'Sales Representative',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Middle-class family in Bangalore. Father works in a private shop. Mother is a housewife. One sister.',
    bio: 'Working in retail sales. Down-to-earth, active, and practicing. Looking for an educated, simple, and modest girl with a positive mindset.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    id: '60d5ecb86f67a213e4b7b368',
    userId: '60d5ecb86f67a213e4b7b378',
    email: 'sample_salma_bano@example.com',
    fullName: 'Salma Bano',
    gender: 'Female',
    dateOfBirth: '1998-04-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900138',
    city: 'Jaipur',
    locality: 'Johri Bazar',
    state: 'Rajasthan',
    country: 'India',
    education: 'B.A. Literature',
    occupation: 'Office Assistant',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Traditional family. Father is a retired artisan. Mother is a homemaker. One younger brother.',
    bio: 'Modest and quiet girl. Working in administration support. Deeply value family respect and daily prayers. Seeking a sincere, settled match.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b369',
    userId: '60d5ecb86f67a213e4b7b379',
    email: 'sample_waseem_akram@example.com',
    fullName: 'Waseem Akram',
    gender: 'Male',
    dateOfBirth: '1996-07-15',
    maritalStatus: 'Single',
    phoneNumber: '+919999900139',
    city: 'Hyderabad',
    locality: 'Tolichowki',
    state: 'Telangana',
    country: 'India',
    education: 'B.Com',
    occupation: 'Senior Clerk',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Middle-class Hyderabad family. Father is retired. Mother is a housewife. One brother.',
    bio: 'Working as senior office administrator. Sincere, soft-spoken, and family-oriented. Striving to live according to Islamic values. Looking for a modest match.',
    themeColor: 'hsl(150, 45%, 18%)', // Emerald
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b370',
    userId: '60d5ecb86f67a213e4b7b380',
    email: 'sample_nida_receptionist@example.com',
    fullName: 'Nida Fatima',
    gender: 'Female',
    dateOfBirth: '2003-12-01',
    maritalStatus: 'Single',
    phoneNumber: '+919999900140',
    city: 'Ghaziabad',
    locality: 'Vasundhara',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.A.',
    occupation: 'Receptionist',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Respectable service family. Father runs a small repair shop. Mother is a housewife.',
    bio: 'Grounded and family-focused receptionist. Value piety, simplicity, and moral limits. Seeking a kind and responsible husband.',
    themeColor: 'hsl(330, 45%, 25%)', // Rose
    verificationStatus: 'APPROVED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: '2026-06-13',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },

  // ==================== 5. QUEUE / ADMIN SIMULATOR TEST CASES (6 Profiles) ====================
  // Criteria: verificationStatus is PENDING, REJECTED, or NEEDS_FOLLOW_UP (so they show up in admin, but not in public categories)
  {
    id: '60d5ecb86f67a213e4b7b401',
    userId: '60d5ecb86f67a213e4b7b411',
    email: 'sample_test_pending_1@example.com',
    fullName: 'Tariq Siddiqui',
    gender: 'Male',
    dateOfBirth: '2000-02-10',
    maritalStatus: 'Single',
    phoneNumber: '+919999900201',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.Tech IT',
    occupation: 'Web Designer',
    annualIncomeRange: '₹5 LPA - ₹10 LPA',
    familyInfo: 'Middle-class family. Father is a school teacher. Mother is a housewife.',
    bio: 'Newly registered user. Working in web design. Quiet and family-oriented.',
    themeColor: 'hsl(150, 45%, 18%)',
    verificationStatus: 'PENDING',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: '2026-06-15',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    id: '60d5ecb86f67a213e4b7b402',
    userId: '60d5ecb86f67a213e4b7b412',
    email: 'sample_test_pending_2@example.com',
    fullName: 'Saima Sheikh',
    gender: 'Female',
    dateOfBirth: '2002-07-17',
    maritalStatus: 'Single',
    phoneNumber: '+919999900202',
    city: 'Aligarh',
    locality: 'Civil Lines',
    state: 'Uttar Pradesh',
    country: 'India',
    education: 'B.Sc Chemistry',
    occupation: 'Student',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Father is a retired AMU employee. Mother is a homemaker. One brother.',
    bio: 'Student. Registered for family-assisted match. Striving to practice Deen.',
    themeColor: 'hsl(200, 45%, 18%)',
    verificationStatus: 'PENDING',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'good_profile',
    regDate: '2026-06-15',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b403',
    userId: '60d5ecb86f67a213e4b7b413',
    email: 'sample_test_rejected_1@example.com',
    fullName: 'Gauhar Khan',
    gender: 'Female',
    dateOfBirth: '1999-06-23',
    maritalStatus: 'Single',
    phoneNumber: '+919999900203',
    city: 'Mumbai',
    locality: 'Juhu',
    state: 'Maharashtra',
    country: 'India',
    education: 'BBA',
    occupation: 'Fashion Model',
    annualIncomeRange: '₹8 LPA - ₹12 LPA',
    familyInfo: 'Mother is a designer. Father is in imports. Modern family.',
    bio: 'Model in Mumbai. Looking for modern Muslim match. (Simulated verification rejection due to invalid phone number).',
    themeColor: 'hsl(330, 45%, 25%)',
    verificationStatus: 'REJECTED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: '2026-05-30',
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    id: '60d5ecb86f67a213e4b7b404',
    userId: '60d5ecb86f67a213e4b7b414',
    email: 'sample_test_rejected_2@example.com',
    fullName: 'Sajid Qureshi',
    gender: 'Male',
    dateOfBirth: '1995-07-12',
    maritalStatus: 'Single',
    phoneNumber: '+919999900204',
    city: 'Hyderabad',
    locality: 'Secunderabad',
    state: 'Telangana',
    country: 'India',
    education: 'High School',
    occupation: 'Delivery Boy',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Parents live in Hyderabad.',
    bio: 'Delivery agent looking for bride. (Simulated verification rejection due to invalid profile documents).',
    themeColor: 'hsl(150, 45%, 18%)',
    verificationStatus: 'REJECTED',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: '2026-06-01',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    id: '60d5ecb86f67a213e4b7b405',
    userId: '60d5ecb86f67a213e4b7b415',
    email: 'sample_test_follow_1@example.com',
    fullName: 'Zeenat Masood',
    gender: 'Female',
    dateOfBirth: '1998-09-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900205',
    city: 'Bhopal',
    locality: 'Arera Colony',
    state: 'Madhya Pradesh',
    country: 'India',
    education: 'B.A.',
    occupation: 'Online Tutor',
    annualIncomeRange: 'Under ₹3 LPA',
    familyInfo: 'Father is retired. Mother is a housewife. One sister.',
    bio: 'Private online teacher. Love reading. (Verification marked as Needs Follow Up for document re-upload).',
    themeColor: 'hsl(330, 45%, 25%)',
    verificationStatus: 'NEEDS_FOLLOW_UP',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: '2026-06-15',
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    id: '60d5ecb86f67a213e4b7b406',
    userId: '60d5ecb86f67a213e4b7b416',
    email: 'sample_test_follow_2@example.com',
    fullName: 'Sohail Hashmi',
    gender: 'Male',
    dateOfBirth: '1997-09-20',
    maritalStatus: 'Single',
    phoneNumber: '+919999900206',
    city: 'Bengaluru',
    locality: 'Whitefield',
    state: 'Karnataka',
    country: 'India',
    education: 'B.E.',
    occupation: 'Junior Support Executive',
    annualIncomeRange: '₹3 LPA - ₹5 LPA',
    familyInfo: 'Father is retired. Mother is a housewife. One sister.',
    bio: 'Working in tech support in Bengaluru. Quiet, simple, practicing. (Verification marked as Needs Follow Up).',
    themeColor: 'hsl(150, 45%, 18%)',
    verificationStatus: 'NEEDS_FOLLOW_UP',
    profileCompletionStatus: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: '2026-06-15',
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Hashmi',
  },
];
