import { PrismaClient, Role, AccountStatus, VerificationStatus, ProfileCompletionStatus, PackageType, PaymentStatus, ApprovalStatus } from '@prisma/client';
import { DEFAULT_MASLAKS, DEFAULT_FIQHS, DEFAULT_CASTES, DEFAULT_LOCATIONS } from '../src/lib/masterData';

const prisma = new PrismaClient();


const profilesToSeed = [
  // ==================== 1. GOOD PROFILES PACKAGE (₹5,500) ====================
  // Criteria: Single, First Marriage, decent job (no doctor/engineer/business/professional), income < 10 LPA
  {
    email: 'sample_adnan_siddiqui@rishteforever.sample',
    name: 'Adnan Siddiqui',
    gender: 'Male',
    dob: new Date(1997, 2, 5),
    maritalStatus: 'Single',
    phone: '+919999900101',
    city: 'Delhi',
    locality: 'Karol Bagh',
    state: 'Delhi',
    education: 'MBA in Logistics',
    occupation: 'Export Firm Manager',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Well-settled family in Central Delhi. Father is a retired exporter. Mother is a housewife. One elder brother.',
    bio: 'Down-to-earth and family-oriented. Working in logistics management. Looking for a pious, educated life partner who balances family values and modern life.',
    theme: 'hsl(42, 58%, 53%)', // Gold
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-05-20'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    email: 'sample_zainab_ahmed@rishteforever.sample',
    name: 'Zainab Ahmed',
    gender: 'Female',
    dob: new Date(2002, 1, 14),
    maritalStatus: 'Single',
    phone: '+919999900102',
    city: 'Noida',
    locality: 'Sector 62',
    state: 'Uttar Pradesh',
    education: 'B.A. English Literature',
    occupation: 'Content Writer',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Father is a retired administrative officer. Mother is a homemaker. One elder sister, married.',
    bio: 'Avid reader and creative writer. Strive to maintain a balance of Deen and Dunya. Looking for a responsible, gentle companion who values simple living.',
    theme: 'hsl(200, 45%, 18%)', // Navy
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-01'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_yasmin_alvi@rishteforever.sample',
    name: 'Yasmin Alvi',
    gender: 'Female',
    dob: new Date(1998, 11, 3),
    maritalStatus: 'Single',
    phone: '+919999900103',
    city: 'Aligarh',
    locality: 'Civil Lines',
    state: 'Uttar Pradesh',
    education: 'M.Sc Chemistry',
    occupation: 'Lecturer',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Academic background. Father is an AMU professor. Mother is a housewife. Two brothers, both settled.',
    bio: 'Passionate educator who loves gardening and literature. Seeking a well-educated, respectful partner who holds high moral values and respect for elders.',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-07'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Alvi',
  },
  {
    email: 'sample_sameer_deshmukh@rishteforever.sample',
    name: 'Sameer Deshmukh',
    gender: 'Male',
    dob: new Date(1998, 7, 22),
    maritalStatus: 'Single',
    phone: '+919999900104',
    city: 'Bhopal',
    locality: 'Arera Colony',
    state: 'Madhya Pradesh',
    education: 'B.Sc Economics',
    occupation: 'Tax Consultant',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Respectable service-class family. Father is a state government employee. Mother is a teacher. One younger sister.',
    bio: 'Sincere, disciplined, and family-oriented. Working as an independent tax advisor. Seeking an educated girl with traditional Islamic ethics.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-08'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    email: 'sample_tarannum_jehan@rishteforever.sample',
    name: 'Tarannum Jehan',
    gender: 'Female',
    dob: new Date(2000, 9, 29),
    maritalStatus: 'Single',
    phone: '+919999900105',
    city: 'Ghaziabad',
    locality: 'Indirapuram',
    state: 'Uttar Pradesh',
    education: 'B.Ed, B.Sc',
    occupation: 'School Teacher',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Middle-class family. Father is a bank accountant. Mother is a homemaker. Two younger sisters.',
    bio: 'Warm and caring primary school teacher. I love children, crafts, and baking. Seeking a gentle and responsible life partner who values education and simple living.',
    theme: 'hsl(200, 45%, 18%)', // Navy
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-09'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_raza_murad@rishteforever.sample',
    name: 'Raza Murad',
    gender: 'Male',
    dob: new Date(2001, 1, 5),
    maritalStatus: 'Single',
    phone: '+919999900106',
    city: 'Noida',
    locality: 'Sector 15',
    state: 'Uttar Pradesh',
    education: 'B.Sc Computer Science',
    occupation: 'QA Analyst',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father runs a retail electrical store. Mother is a housewife. One younger brother.',
    bio: 'Working as a QA analyst in Noida. Love fitness, reading, and learning new things. Looking for a positive, cheerful girl who values family values and Deen.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-10'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    email: 'sample_farah_sheikh@rishteforever.sample',
    name: 'Farah Sheikh',
    gender: 'Female',
    dob: new Date(1999, 4, 15),
    maritalStatus: 'Single',
    phone: '+919999900107',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    education: 'MBA in HR',
    occupation: 'HR Recruiter',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Respectable Lucknow family. Father is a senior lawyer. Mother is a housewife. One brother.',
    bio: 'Dynamic yet humble. Striving to practice Islamic principles in daily life. Looking for a supportive companion who is well-settled and respectful.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-11'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_arshad_warsi@rishteforever.sample',
    name: 'Arshad Warsi',
    gender: 'Male',
    dob: new Date(1999, 10, 25),
    maritalStatus: 'Single',
    phone: '+919999900108',
    city: 'Jaipur',
    locality: 'Johri Bazar',
    state: 'Rajasthan',
    education: 'B.Arch',
    occupation: 'Architectural Consultant',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Artisan family. Father is a jewelry designer. Mother is a homemaker. Two brothers.',
    bio: 'Working as an architectural designer in Jaipur. I value honesty, simple living, and prayers. Looking for an educated, modest girl with traditional values.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-12'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Mughal',
  },
  {
    email: 'sample_sobia_qureshi@rishteforever.sample',
    name: 'Sobia Qureshi',
    gender: 'Female',
    dob: new Date(2001, 8, 12),
    maritalStatus: 'Single',
    phone: '+919999900109',
    city: 'Delhi',
    locality: 'Daryaganj',
    state: 'Delhi',
    education: 'B.Des Fashion Design',
    occupation: 'Fashion Consultant',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Upper middle-class. Father runs a pharmaceutical trading firm. Mother is a homemaker. One brother.',
    bio: 'Creative, optimistic, and deeply religious. Love art, travel, and cooking. Seeking a practicing Sunni gentleman with good education and high values.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    email: 'sample_imran_mansuri@rishteforever.sample',
    name: 'Imran Mansuri',
    gender: 'Male',
    dob: new Date(1996, 5, 24),
    maritalStatus: 'Single',
    phone: '+919999900110',
    city: 'Mumbai',
    locality: 'Kurla',
    state: 'Maharashtra',
    education: 'M.Com',
    occupation: 'Operations Supervisor',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father runs a general retail store. Mother is a homemaker. Two younger sisters, studying.',
    bio: 'Responsible, soft-spoken, and helpful. Working as an operations supervisor in Mumbai. Striving to balance Deen and Dunya. Looking for a modest bride.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'good_profile_package',
    packagePrice: 5500,
    category: 'good_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Mansuri',
  },

  // ==================== 2. SECOND MARRIAGE PACKAGE (₹11,000) ====================
  // Criteria: Divorced/Widowed, mix male/female, under 10LPA income, occupations avoiding high profile keywords
  {
    email: 'sample_aisha_rahman@rishteforever.sample',
    name: 'Aisha Rahman',
    gender: 'Female',
    dob: new Date(1995, 8, 20),
    maritalStatus: 'Divorced',
    phone: '+919999900111',
    city: 'Bengaluru',
    locality: 'Indiranagar',
    state: 'Karnataka',
    education: 'M.Tech Computer Science',
    occupation: 'Senior Web Developer',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Educated family. Father is an administrator, mother is a teacher. Two sisters, both happily married.',
    bio: 'Simple and pious. software professional. Divorced after a short marriage (no children). Seeking a clean-hearted, responsible partner for a fresh start.',
    theme: 'hsl(175, 45%, 20%)', // Teal
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-05-15'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    email: 'sample_farhan_syed@rishteforever.sample',
    name: 'Farhan Syed',
    gender: 'Male',
    dob: new Date(1991, 3, 10),
    maritalStatus: 'Divorced',
    phone: '+919999900112',
    city: 'Mumbai',
    locality: 'Andheri West',
    state: 'Maharashtra',
    education: 'B.Sc IT',
    occupation: 'Technical Lead',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father is a retired banking officer. Mother is a homemaker. No siblings. Living in own apartment.',
    bio: 'Seeking a second chance at marriage based on mutual respect and clarity. Divorced. Striving to practice daily prayers. Looking for an understanding partner.',
    theme: 'hsl(42, 58%, 53%)', // Gold
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-04-20'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    email: 'sample_mariam_fatimah@rishteforever.sample',
    name: 'Mariam Fatimah',
    gender: 'Female',
    dob: new Date(1992, 5, 18),
    maritalStatus: 'Widowed',
    phone: '+919999900113',
    city: 'Jaipur',
    locality: 'C-Scheme',
    state: 'Rajasthan',
    education: 'M.Com',
    occupation: 'Accountant',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father is a general merchant. Mother is a teacher. One younger brother.',
    bio: 'Pious, independent widow. Mother of a 4-year-old daughter. Looking for a compassionate partner who can be a loving husband and a caring father figure.',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-05-01'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Pathan',
  },
  {
    email: 'sample_shabana_bano@rishteforever.sample',
    name: 'Shabana Bano',
    gender: 'Female',
    dob: new Date(1986, 2, 14),
    maritalStatus: 'Divorced',
    phone: '+919999900114',
    city: 'Lucknow',
    locality: 'Aliganj',
    state: 'Uttar Pradesh',
    education: 'B.A. Urdu',
    occupation: 'Senior Homemaker',
    income: 'Under ₹3 LPA',
    family: 'Traditional family. Father is retired. Three brothers, all married and settled.',
    bio: 'Caring, soft-spoken, and domestic. Divorced. Mother of a 10-year-old son who lives with me. Seeking a respectful and mature partner to rebuild a peaceful home.',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-05-10'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    email: 'sample_imran_malik@rishteforever.sample',
    name: 'Imran Malik',
    gender: 'Male',
    dob: new Date(1984, 8, 30),
    maritalStatus: 'Widowed',
    phone: '+919999900115',
    city: 'Ghaziabad',
    locality: 'Raj Nagar',
    state: 'Uttar Pradesh',
    education: 'B.Sc Chemistry',
    occupation: 'Shop Proprietor',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Middle-class family. Living with two kids (ages 12 and 8). Father has retired.',
    bio: 'Widower seeking a kind, nurturing companion to rebuild a warm home. I run a retail electrical store. Value family values, piety, and mutual support.',
    theme: 'hsl(42, 58%, 53%)', // Gold
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-05-12'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    email: 'sample_hina_shaheen@rishteforever.sample',
    name: 'Hina Shaheen',
    gender: 'Female',
    dob: new Date(1995, 10, 15),
    maritalStatus: 'Divorced',
    phone: '+919999900116',
    city: 'Bhopal',
    locality: 'Jahangirabad',
    state: 'Madhya Pradesh',
    education: 'M.A. Literature',
    occupation: 'Creative Writer',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Father is a retired administrative clerk. Mother is a housewife. One sister, married.',
    bio: 'Divorced. Quiet and creative. Working as a content editor and writer. Looking for a partner who is honest, understands mutual respect, and practices Deen.',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-06-12'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Pathan',
  },
  {
    email: 'sample_javed_jaffrey@rishteforever.sample',
    name: 'Javed Jaffrey',
    gender: 'Male',
    dob: new Date(1995, 0, 15),
    maritalStatus: 'Divorced',
    phone: '+919999900117',
    city: 'Mumbai',
    locality: 'Colaba',
    state: 'Maharashtra',
    education: 'MBA in Marketing',
    occupation: 'Marketing Manager',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father is a retired merchant navy officer. Mother is a homemaker. One brother.',
    bio: 'Seeking a second marriage. Divorced. Modern outlook but grounded in values. Loves fitness, reading, and travel. Seeking a mature, understanding life partner.',
    theme: 'hsl(42, 58%, 53%)', // Gold
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_rehana_parveen@rishteforever.sample',
    name: 'Rehana Parveen',
    gender: 'Female',
    dob: new Date(1996, 3, 20),
    maritalStatus: 'Divorced',
    phone: '+919999900118',
    city: 'Delhi',
    locality: 'Zakir Nagar',
    state: 'Delhi',
    education: 'B.A. Education',
    occupation: 'Primary School Teacher',
    income: 'Under ₹3 LPA',
    family: 'Simple, respectable family in South Delhi. Father runs a book store. Two brothers.',
    bio: 'Soft-hearted and caring. Divorced. Working as a primary school teacher in a local institution. Looking for a simple, sincere, and family-oriented partner.',
    theme: 'hsl(200, 45%, 18%)', // Navy
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_salman_baig@rishteforever.sample',
    name: 'Salman Baig',
    gender: 'Male',
    dob: new Date(1990, 1, 15),
    maritalStatus: 'Divorced',
    phone: '+919999900119',
    city: 'Lucknow',
    locality: 'Aminabad',
    state: 'Uttar Pradesh',
    education: 'High School',
    occupation: 'Retail Merchant',
    income: 'Under ₹3 LPA',
    family: 'Middle-class family in old Lucknow. Parents live with me. One sister.',
    bio: 'Sincere, down-to-earth shopkeeper. Divorced. Seeking a simple, pious girl who values family attachment and religious traditions.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Mughal',
  },
  {
    email: 'sample_nisar_sheikh@rishteforever.sample',
    name: 'Nisar Sheikh',
    gender: 'Male',
    dob: new Date(1988, 5, 12),
    maritalStatus: 'Widowed',
    phone: '+919999900120',
    city: 'Hyderabad',
    locality: 'Tolichowki',
    state: 'Telangana',
    education: 'B.Com',
    occupation: 'Senior Clerk',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Respectable family from Hyderabad. No children. Living with elderly parents.',
    bio: 'Widower. Quiet, disciplined, and practicing Sunni. Working as a senior office clerk. Seeking an educated, caring woman for a long-term Nikah relationship.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'second_marriage_package',
    packagePrice: 11000,
    category: 'second_marriage',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },

  // ==================== 3. HIGH PROFILE PACKAGE (₹21,000) ====================
  // Criteria: Single, First Marriage, Doctor/Engineer/Business/Corporate Professional, Income ₹10 LPA+
  {
    email: 'sample_sarah_khan@rishteforever.sample',
    name: 'Dr. Sarah Khan',
    gender: 'Female',
    dob: new Date(1999, 4, 12),
    maritalStatus: 'Single',
    phone: '+919999900121',
    city: 'Mumbai',
    locality: 'Bandra West',
    state: 'Maharashtra',
    education: 'MD, MBBS',
    occupation: 'Pediatrician (Doctor)',
    income: '₹12 LPA - ₹15 LPA',
    family: 'Highly educated family. Father is a retired university professor. Mother is a homemaker. One younger brother, studying in the US.',
    bio: 'Pious, compassionate, and career-oriented. Striving to manage professional growth and Islamic values. Looking for a highly educated partner (Doctor/Engineer/MBA).',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-04-10'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    email: 'sample_nida_fatma@rishteforever.sample',
    name: 'Nida Fatma',
    gender: 'Female',
    dob: new Date(1997, 8, 9),
    maritalStatus: 'Single',
    phone: '+919999900122',
    city: 'Hyderabad',
    locality: 'Jubilee Hills',
    state: 'Telangana',
    education: 'MBBS, MD',
    occupation: 'Resident Gynecologist (Doctor)',
    income: '₹10 LPA - ₹15 LPA',
    family: 'Elite Hyderabad family. Father is an orthopedic surgeon. Mother is a senior doctor. One brother (tech engineer).',
    bio: 'Currently doing postgraduate residency. Balanced, career-oriented yet values traditional family life. Seeking a professional partner with good character.',
    theme: 'hsl(345, 65%, 28%)', // Crimson
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    email: 'sample_mansoor_ali@rishteforever.sample',
    name: 'Mansoor Ali',
    gender: 'Male',
    dob: new Date(1997, 8, 20),
    maritalStatus: 'Single',
    phone: '+919999900123',
    city: 'Bengaluru',
    locality: 'Whitefield',
    state: 'Karnataka',
    education: 'M.S. Data Science',
    occupation: 'Lead AI Professional',
    income: '₹15 LPA - ₹25 LPA',
    family: 'Intellectual family. Father is a retired corporate scientist. Mother is a private school principal. One brother.',
    bio: 'Data scientist in Bengaluru. Practice Islamic values and balance with corporate lifestyle. Looking for a partner who is educated, positive, and religious.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-12'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    email: 'sample_tariq_anwar@rishteforever.sample',
    name: 'Tariq Anwar',
    gender: 'Male',
    dob: new Date(1994, 5, 15),
    maritalStatus: 'Single',
    phone: '+919999900124',
    city: 'Pune',
    locality: 'Deccan Gymkhana',
    state: 'Maharashtra',
    education: 'B.Tech in Computer Science',
    occupation: 'Senior Software Engineer',
    income: '₹15 LPA - ₹25 LPA',
    family: 'Father is an executive engineer. Mother is a housewife. One sister, married.',
    bio: 'Working as a Senior Developer in Pune. Sincere, loving, and focused on prayers. Seeking an educated, modest, and family-oriented life partner.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    email: 'sample_khalid_masood@rishteforever.sample',
    name: 'Khalid Masood',
    gender: 'Male',
    dob: new Date(1992, 10, 18),
    maritalStatus: 'Single',
    phone: '+919999900125',
    city: 'Delhi',
    locality: 'Connaught Place',
    state: 'Delhi',
    education: 'MBA from FMS Delhi',
    occupation: 'Premium Business Owner',
    income: 'Above ₹25 LPA',
    family: 'Premium business family in Delhi. Owns chain of medical supplies. One brother, one sister.',
    bio: 'Managing family business and startup. Ambitious, down-to-earth, and practicing. Looking for a modern, well-educated, and religious life partner.',
    theme: 'hsl(42, 58%, 53%)', // Gold
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_faisal_qureshi@rishteforever.sample',
    name: 'Faisal Qureshi',
    gender: 'Male',
    dob: new Date(1994, 6, 25),
    maritalStatus: 'Single',
    phone: '+919999900126',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    education: 'MD Medicine',
    occupation: 'Consultant Cardiologist (Doctor)',
    income: '₹15 LPA - ₹25 LPA',
    family: 'Respected Lucknow family. Father runs a pharmaceutical trading firm. Mother is a housewife. One sister.',
    bio: 'Practicing cardiologist. Calm, dedicated, and family-oriented. Striving for a pure lifestyle. Seeking a highly educated girl with a warm heart.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-05'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    email: 'sample_asma_siddiqui@rishteforever.sample',
    name: 'Asma Siddiqui',
    gender: 'Female',
    dob: new Date(1998, 1, 10),
    maritalStatus: 'Single',
    phone: '+919999900127',
    city: 'Delhi',
    locality: 'Okhla',
    state: 'Delhi',
    education: 'Chartered Accountant (CA)',
    occupation: 'Chartered Accountant (Professional)',
    income: '₹12 LPA - ₹15 LPA',
    family: 'Middle-class. Father is an accountant in Delhi. Mother is a homemaker. One younger brother, CA student.',
    bio: 'Working as a Senior Auditor. Independent, religious, and soft-spoken. Seeking a practicing professional with high ethics and clean habits.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    email: 'sample_riaz_ahmed@rishteforever.sample',
    name: 'Riaz Ahmed',
    gender: 'Male',
    dob: new Date(1993, 2, 28),
    maritalStatus: 'Single',
    phone: '+919999900128',
    city: 'Hyderabad',
    locality: 'Banjara Hills',
    state: 'Telangana',
    education: 'LL.M from NLSIU Bangalore',
    occupation: 'Corporate Lawyer (Professional)',
    income: '₹15 LPA - ₹25 LPA',
    family: 'Father is a retired judge. Mother is a lecturer. Two sisters, married.',
    bio: 'Corporate legal counsel in Hyderabad. Religious, values truth and family. Seeking an educated, pious girl who can manage home and values with grace.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    email: 'sample_zainab_malik@rishteforever.sample',
    name: 'Zainab Malik',
    gender: 'Female',
    dob: new Date(1996, 7, 15),
    maritalStatus: 'Single',
    phone: '+919999900129',
    city: 'Mumbai',
    locality: 'Juhu',
    state: 'Maharashtra',
    education: 'MBA from NMIMS Mumbai',
    occupation: 'Management Consultant (Professional)',
    income: '₹12 LPA - ₹15 LPA',
    family: 'Father is a private company director. Mother runs an Islamic charity school. One sister.',
    bio: 'Working in advisory consulting. Pious, modest, and travel lover. Seeking a well-settled professional Sunni groom with good education and character.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    email: 'sample_kamran_surgeon@rishteforever.sample',
    name: 'Dr. Kamran Khan',
    gender: 'Male',
    dob: new Date(1991, 11, 20),
    maritalStatus: 'Single',
    phone: '+919999900130',
    city: 'Bhopal',
    locality: 'Shahpura',
    state: 'Madhya Pradesh',
    education: 'MS General Surgery',
    occupation: 'Senior Surgeon (Doctor)',
    income: 'Above ₹25 LPA',
    family: 'Doctor family. Father is a retired medical director. Mother is a gynecologist. Two brothers.',
    bio: 'Working as a Consultant Surgeon in Bhopal. Grounded, focused on Deen, and loves humanitarian work. Seeking an educated, pious Muslim girl.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'high_profile_package',
    packagePrice: 21000,
    category: 'high_profile',
    regDate: new Date('2026-06-14'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },

  // ==================== 4. STANDARD/MONTHLY MEMBERSHIP PROFILES (₹300) ====================
  // Criteria: Single, First Marriage, normal job (no doctor/engineer/business/professional), income < 10 LPA
  {
    email: 'sample_bilal_chishti@rishteforever.sample',
    name: 'Bilal Chishti',
    gender: 'Male',
    dob: new Date(2000, 5, 12),
    maritalStatus: 'Single',
    phone: '+919999900131',
    city: 'Delhi',
    locality: 'Okhla',
    state: 'Delhi',
    education: 'M.Tech',
    occupation: 'Research Scholar',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Noble middle-class family. Father is retired. Mother is a housewife. One sister.',
    bio: 'Academic researcher, quiet and thoughtful. Deeply value honesty and prayers. Looking for an educated partner who values simple living.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Syed / Sayyid',
  },
  {
    email: 'sample_sana_parveen@rishteforever.sample',
    name: 'Sana Parveen',
    gender: 'Female',
    dob: new Date(2001, 2, 28),
    maritalStatus: 'Single',
    phone: '+919999900132',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    education: 'B.FA in Applied Arts',
    occupation: 'Graphic Artist',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Artist family. Father has printing shop. Mother is a homemaker. One sister.',
    bio: 'Creative web illustrator and graphic artist. Striving to follow Deen and live peacefully. Seeking a simple and helpful partner with sound education.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    email: 'sample_kamran_ansari@rishteforever.sample',
    name: 'Kamran Ansari',
    gender: 'Male',
    dob: new Date(1998, 11, 1),
    maritalStatus: 'Single',
    phone: '+919999900133',
    city: 'Bhopal',
    locality: 'Shahpura',
    state: 'Madhya Pradesh',
    education: 'B.Sc in Biotechnology',
    occupation: 'Lab Technician',
    income: 'Under ₹3 LPA',
    family: 'Respectable service family. Father is a security supervisor. Mother is a homemaker.',
    bio: 'Working as a lab technician in Bhopal. Simple, honest, and helpful. Looking for a modest, domestic girl who is family-oriented.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Ansari',
  },
  {
    email: 'sample_sameera_begum@rishteforever.sample',
    name: 'Sameera Begum',
    gender: 'Female',
    dob: new Date(2000, 3, 20),
    maritalStatus: 'Single',
    phone: '+919999900134',
    city: 'Hyderabad',
    locality: 'Charminar',
    state: 'Telangana',
    education: 'B.Ed, B.A.',
    occupation: 'Primary Teacher',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Middle-class family from old city Hyderabad. Father is retired. Mother is a housewife. One sister.',
    bio: 'Simple primary school teacher. I value prayers, modesty, and family. Seeking an honest and supportive life partner who resides in Hyderabad.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_farooq_sheikh@rishteforever.sample',
    name: 'Farooq Sheikh',
    gender: 'Male',
    dob: new Date(1996, 6, 12),
    maritalStatus: 'Single',
    phone: '+919999900135',
    city: 'Mumbai',
    locality: 'Kurla',
    state: 'Maharashtra',
    education: 'B.Com',
    occupation: 'Customer Executive',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Middle-class Kurla family. Father runs a tailoring shop. Mother is a homemaker. One younger brother.',
    bio: 'Working in customer operations. Sincere, hard-working, and focused on Deen. Seeking a helpful, domestic girl who is family-oriented and respectful.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_humaira_qureshi@rishteforever.sample',
    name: 'Humaira Qureshi',
    gender: 'Female',
    dob: new Date(2001, 5, 23),
    maritalStatus: 'Single',
    phone: '+919999900136',
    city: 'Delhi',
    locality: 'Zakir Nagar',
    state: 'Delhi',
    education: 'B.Des in Fashion',
    occupation: 'Fashion Stylist',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Father runs a small garment manufacturing unit. Mother is a homemaker. One brother.',
    bio: 'Stylist in Delhi. Creative, cheerful, and modest. Values traditional boundaries and prayers. Seeking a supportive Sunni gentleman.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    email: 'sample_majid_malik@rishteforever.sample',
    name: 'Majid Malik',
    gender: 'Male',
    dob: new Date(1997, 8, 20),
    maritalStatus: 'Single',
    phone: '+919999900137',
    city: 'Bengaluru',
    locality: 'Indiranagar',
    state: 'Karnataka',
    education: 'B.BA',
    occupation: 'Sales Representative',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Middle-class family in Bangalore. Father works in a private shop. Mother is a housewife. One sister.',
    bio: 'Working in retail sales. Down-to-earth, active, and practicing. Looking for an educated, simple, and modest girl with a positive mindset.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Malik',
  },
  {
    email: 'sample_salma_bano@rishteforever.sample',
    name: 'Salma Bano',
    gender: 'Female',
    dob: new Date(1998, 3, 20),
    maritalStatus: 'Single',
    phone: '+919999900138',
    city: 'Jaipur',
    locality: 'Johri Bazar',
    state: 'Rajasthan',
    education: 'B.A. Literature',
    occupation: 'Office Assistant',
    income: 'Under ₹3 LPA',
    family: 'Traditional family. Father is a retired artisan. Mother is a homemaker. One younger brother.',
    bio: 'Modest and quiet girl. Working in administration support. Deeply value family respect and daily prayers. Seeking a sincere, settled match.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_waseem_akram@rishteforever.sample',
    name: 'Waseem Akram',
    gender: 'Male',
    dob: new Date(1996, 6, 15),
    maritalStatus: 'Single',
    phone: '+919999900139',
    city: 'Hyderabad',
    locality: 'Tolichowki',
    state: 'Telangana',
    education: 'B.Com',
    occupation: 'Senior Clerk',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Middle-class Hyderabad family. Father is retired. Mother is a housewife. One brother.',
    bio: 'Working as senior office administrator. Sincere, soft-spoken, and family-oriented. Striving to live according to Islamic values. Looking for a modest match.',
    theme: 'hsl(150, 45%, 18%)', // Emerald
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_nida_receptionist@rishteforever.sample',
    name: 'Nida Fatima',
    gender: 'Female',
    dob: new Date(2003, 11, 1),
    maritalStatus: 'Single',
    phone: '+919999900140',
    city: 'Ghaziabad',
    locality: 'Vasundhara',
    state: 'Uttar Pradesh',
    education: 'B.A.',
    occupation: 'Receptionist',
    income: 'Under ₹3 LPA',
    family: 'Respectable service family. Father runs a small repair shop. Mother is a housewife.',
    bio: 'Grounded and family-focused receptionist. Value piety, simplicity, and moral limits. Seeking a kind and responsible husband.',
    theme: 'hsl(330, 45%, 25%)', // Rose
    verification: 'APPROVED',
    completion: 'COMPLETE',
    hasPaid: true,
    packageType: 'monthly_membership',
    packagePrice: 300,
    category: 'normal',
    regDate: new Date('2026-06-13'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },

  // ==================== 5. QUEUE / ADMIN QUEUE TEST CASES (6 Profiles) ====================
  // Criteria: verificationStatus is PENDING, REJECTED, or NEEDS_FOLLOW_UP (so they show up in admin, but not in public categories)
  {
    email: 'sample_test_pending_1@rishteforever.sample',
    name: 'Tariq Siddiqui',
    gender: 'Male',
    dob: new Date(2000, 1, 10),
    maritalStatus: 'Single',
    phone: '+919999900201',
    city: 'Lucknow',
    locality: 'Hazratganj',
    state: 'Uttar Pradesh',
    education: 'B.Tech IT',
    occupation: 'Web Designer',
    income: '₹5 LPA - ₹10 LPA',
    family: 'Middle-class family. Father is a school teacher. Mother is a housewife.',
    bio: 'Newly registered user. Working in web design. Quiet and family-oriented.',
    theme: 'hsl(150, 45%, 18%)',
    verification: 'PENDING',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: new Date('2026-06-15'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Siddiqui',
  },
  {
    email: 'sample_test_pending_2@rishteforever.sample',
    name: 'Saima Sheikh',
    gender: 'Female',
    dob: new Date(2002, 6, 17),
    maritalStatus: 'Single',
    phone: '+919999900202',
    city: 'Aligarh',
    locality: 'Civil Lines',
    state: 'Uttar Pradesh',
    education: 'B.Sc Chemistry',
    occupation: 'Student',
    income: 'Under ₹3 LPA',
    family: 'Father is a retired AMU employee. Mother is a homemaker. One brother.',
    bio: 'Student. Registered for family-assisted match. Striving to practice Deen.',
    theme: 'hsl(200, 45%, 18%)',
    verification: 'PENDING',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'good_profile',
    regDate: new Date('2026-06-15'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_test_rejected_1@rishteforever.sample',
    name: 'Gauhar Khan',
    gender: 'Female',
    dob: new Date(1999, 5, 23),
    maritalStatus: 'Single',
    phone: '+919999900203',
    city: 'Mumbai',
    locality: 'Juhu',
    state: 'Maharashtra',
    education: 'BBA',
    occupation: 'Fashion Model',
    income: '₹8 LPA - ₹12 LPA',
    family: 'Mother is a designer. Father is in imports. Modern family.',
    bio: 'Model in Mumbai. Looking for modern Muslim match. (Sample verification rejection due to invalid phone number).',
    theme: 'hsl(330, 45%, 25%)',
    verification: 'REJECTED',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: new Date('2026-05-30'),
    maslak: 'Sunni Barelvi / Ahle Sunnat Wal Jamaat',
    fiqh: 'Hanafi',
    biradari: 'Khan',
  },
  {
    email: 'sample_test_rejected_2@rishteforever.sample',
    name: 'Sajid Qureshi',
    gender: 'Male',
    dob: new Date(1995, 6, 12),
    maritalStatus: 'Single',
    phone: '+919999900204',
    city: 'Hyderabad',
    locality: 'Secunderabad',
    state: 'Telangana',
    education: 'High School',
    occupation: 'Delivery Boy',
    income: 'Under ₹3 LPA',
    family: 'Parents live in Hyderabad.',
    bio: 'Delivery agent looking for bride. (Sample verification rejection due to invalid profile documents).',
    theme: 'hsl(150, 45%, 18%)',
    verification: 'REJECTED',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: new Date('2026-06-01'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Qureshi',
  },
  {
    email: 'sample_test_follow_1@rishteforever.sample',
    name: 'Zeenat Masood',
    gender: 'Female',
    dob: new Date(1998, 8, 20),
    maritalStatus: 'Single',
    phone: '+919999900205',
    city: 'Bhopal',
    locality: 'Arera Colony',
    state: 'Madhya Pradesh',
    education: 'B.A.',
    occupation: 'Online Tutor',
    income: 'Under ₹3 LPA',
    family: 'Father is retired. Mother is a housewife. One sister.',
    bio: 'Private online teacher. Love reading. (Verification marked as Needs Follow Up for document re-upload).',
    theme: 'hsl(330, 45%, 25%)',
    verification: 'NEEDS_FOLLOW_UP',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: new Date('2026-06-15'),
    maslak: 'Sunni Deobandi',
    fiqh: 'Hanafi',
    biradari: 'Sheikh / Shaikh',
  },
  {
    email: 'sample_test_follow_2@rishteforever.sample',
    name: 'Sohail Hashmi',
    gender: 'Male',
    dob: new Date(1997, 8, 20),
    maritalStatus: 'Single',
    phone: '+919999900206',
    city: 'Bengaluru',
    locality: 'Whitefield',
    state: 'Karnataka',
    education: 'B.E.',
    occupation: 'Junior Support Executive',
    income: '₹3 LPA - ₹5 LPA',
    family: 'Father is retired. Mother is a housewife. One sister.',
    bio: 'Working in tech support in Bengaluru. Quiet, simple, practicing. (Verification marked as Needs Follow Up).',
    theme: 'hsl(150, 45%, 18%)',
    verification: 'NEEDS_FOLLOW_UP',
    completion: 'COMPLETE',
    hasPaid: false,
    category: 'normal',
    regDate: new Date('2026-06-15'),
    maslak: 'Sunni',
    fiqh: 'Hanafi',
    biradari: 'Hashmi',
  },
];;

async function main() {
  console.log('Starting sample profiles database seeding...');
  let insertedCount = 0;
  let skippedCount = 0;

  try {
    // 0. Seed Master Data Options if empty
    console.log('Seeding Master Data options if empty...');
    const mCount = await prisma.maslakOption.count();
    if (mCount === 0) {
      await prisma.maslakOption.createMany({
        data: DEFAULT_MASLAKS.map(m => ({ label: m.label, aliases: m.aliases, isDisabled: false }))
      });
      console.log('Seeded Maslak options to DB.');
    }
    const cCount = await prisma.casteOption.count();
    if (cCount === 0) {
      await prisma.casteOption.createMany({
        data: DEFAULT_CASTES.map(c => ({ label: c.label, aliases: c.aliases, isDisabled: false }))
      });
      console.log('Seeded Caste options to DB.');
    }
    const lCount = await prisma.locationOption.count();
    if (lCount === 0) {
      await prisma.locationOption.createMany({
        data: DEFAULT_LOCATIONS.map(l => ({
          state: l.state,
          district: l.district,
          locality: l.locality || null,
          isHighPriority: l.isHighPriority || false,
          isDisabled: false
        }))
      });
      console.log('Seeded Location options to DB.');
    }

    // 1. Create or Find Sample Admin User
    let admin = await prisma.user.findUnique({
      where: { email: 'sample_admin@rishteforever.sample' },
    });
    if (!admin) {
      admin = await prisma.user.create({
        data: {
          name: 'Sample Admin',
          email: 'sample_admin@rishteforever.sample',
          role: Role.ADMIN,
          accountStatus: AccountStatus.ACTIVE,
        },
      });
      console.log('Sample Admin user created.');
    } else {
      console.log('Sample Admin user already exists.');
    }

    // 2. Loop and Create Profiles
    for (const pData of profilesToSeed) {
      // Check if user exists
      const existingUser = await prisma.user.findUnique({
        where: { email: pData.email },
      });

      if (existingUser) {
        skippedCount++;
        continue;
      }

      // Create new User
      const user = await prisma.user.create({
        data: {
          name: pData.name,
          email: pData.email,
          role: Role.USER,
          accountStatus: AccountStatus.ACTIVE,
          createdAt: pData.regDate,
          updatedAt: pData.regDate,
        },
      });

      // Create Matrimonial Profile
      const matProfile = await prisma.matrimonialProfile.create({
        data: {
          userId: user.id,
          fullName: pData.name,
          gender: pData.gender,
          dateOfBirth: pData.dob,
          maritalStatus: pData.maritalStatus,
          phoneNumber: pData.phone,
          city: pData.city,
          areaOrLocality: pData.locality,
          state: pData.state,
          country: 'India',
          education: pData.education,
          occupation: pData.occupation,
          annualIncomeRange: pData.income,
          familyInfo: pData.family,
          bio: pData.bio,
          themeColor: pData.theme,
          verificationStatus: pData.verification as VerificationStatus,
          profileCompletionStatus: pData.completion as ProfileCompletionStatus,
          adminApprovalStatus: pData.verification === 'APPROVED' ? 'APPROVED' : (pData.verification === 'REJECTED' ? 'REJECTED' : 'PENDING'),
          hasPaid: pData.hasPaid,
          category: pData.category || 'normal',
          createdAt: pData.regDate,
          updatedAt: pData.regDate,
          
          // Identity fields:
          maslak: (pData as any).maslak || (pData.gender === 'Female' ? 'Sunni' : 'Sunni Deobandi'),
          fiqh: (pData as any).fiqh || 'Hanafi',
          biradari: (pData as any).biradari || (pData.name.includes('Khan') ? 'Khan' : (pData.name.includes('Siddiqui') ? 'Siddiqui' : (pData.name.includes('Syed') ? 'Syed / Sayyid' : (pData.name.includes('Qureshi') ? 'Qureshi' : (pData.name.includes('Ansari') ? 'Ansari' : 'Sheikh / Shaikh'))))),
          biradariAliases: [],
          district: pData.city,
          locality: pData.locality,
          preferredLocations: [pData.state],
          sameCastePreference: false,
          sameMaslakPreference: false,
          noCastePreference: true,
          noMaslakPreference: true,
          willingToRelocate: true,
        },
      });


      // Create Verification Request record
      await prisma.verificationRequest.create({
        data: {
          profileId: matProfile.id,
          status: pData.verification as VerificationStatus,
          assignedAdminId: (pData.verification === 'APPROVED' || pData.verification === 'REJECTED') ? admin.id : null,
          notes: pData.verification === 'APPROVED' 
            ? 'Verified call completed. Documents approved.' 
            : (pData.verification === 'REJECTED' ? 'Failed verification call. Invalid number.' : 'New profile registration. Queue check required.'),
          verifiedAt: pData.verification === 'APPROVED' ? new Date() : null,
          createdAt: pData.regDate,
          updatedAt: pData.regDate,
        },
      });

      // If Paid, create Package Purchase
      if (pData.hasPaid && pData.packageType) {
        const gstRate = 0.18;
        const total = Math.round(pData.packagePrice! * (1 + gstRate));
        const purchase = await prisma.packagePurchase.create({
          data: {
            profileId: matProfile.id,
            packageType: pData.packageType as PackageType,
            basePrice: pData.packagePrice!,
            gstRate: gstRate,
            totalAmount: total,
            billingType: pData.packageType === 'monthly_membership' ? 'MONTHLY' : 'ONE_TIME',
            successFeeAmount: pData.packageType === 'high_profile_package' ? 25000 : (pData.packageType === 'good_profile_package' ? 21000 : 0),
            razorpayOrderId: `order_sample_${matProfile.id}`,
            razorpayPaymentId: `pay_sample_${matProfile.id}`,
            paymentStatus: PaymentStatus.PAID,
            purchaseDate: pData.regDate,
            expiryDate: pData.packageType === 'monthly_membership' ? new Date(pData.regDate.getTime() + 30 * 24 * 60 * 60 * 1000) : null,
            accessStatus: 'ACTIVE',
            eligibilityStatus: pData.packageType === 'high_profile_package' 
              ? (pData.verification === 'APPROVED' ? ApprovalStatus.APPROVED : ApprovalStatus.PENDING) 
              : ApprovalStatus.APPROVED,
            marriageConfirmation: 'PENDING',
            successFeePaymentStatus: PaymentStatus.PENDING,
            internalNotes: 'Automated sample seed payment.',
            createdAt: pData.regDate,
            updatedAt: pData.regDate,
          },
        });

        // Audit Log for payment verification
        await prisma.auditLog.create({
          data: {
            actorUserId: null,
            action: `PAYMENT_VERIFIED_${pData.packageType}`,
            targetType: 'PackagePurchase',
            targetId: purchase.id,
            metadata: JSON.stringify({ orderId: purchase.razorpayOrderId, paymentId: purchase.razorpayPaymentId }),
            createdAt: pData.regDate,
          },
        });
      }

      // Audit Log for verification status change
      await prisma.auditLog.create({
        data: {
          actorUserId: admin.id,
          action: `VERIFICATION_STATUS_CHANGE_${pData.verification}`,
          targetType: 'MatrimonialProfile',
          targetId: matProfile.id,
          metadata: JSON.stringify({ notes: `Sample setup: status set to ${pData.verification}.` }),
          createdAt: pData.regDate,
        },
      });

      insertedCount++;
    }

    // 3. Seed Curated Lead Assignments
    console.log('Seeding curated leads...');
    const adnan = await prisma.user.findFirst({
      where: { email: 'sample_adnan_siddiqui@rishteforever.sample' },
      include: { profile: true },
    });
    const sarah = await prisma.user.findFirst({
      where: { email: 'sample_sarah_khan@rishteforever.sample' },
      include: { profile: true },
    });
    const farhan = await prisma.user.findFirst({
      where: { email: 'sample_farhan_syed@rishteforever.sample' },
      include: { profile: true },
    });
    const mariam = await prisma.user.findFirst({
      where: { email: 'sample_mariam_fatimah@rishteforever.sample' },
      include: { profile: true },
    });
    const mansoor = await prisma.user.findFirst({
      where: { email: 'sample_mansoor_ali@rishteforever.sample' },
      include: { profile: true },
    });
    const aisha = await prisma.user.findFirst({
      where: { email: 'sample_aisha_rahman@rishteforever.sample' },
      include: { profile: true },
    });

    const leadAssignments = [
      { buyer: adnan, lead: sarah },
      { buyer: farhan, lead: mariam },
      { buyer: mansoor, lead: aisha },
    ];

    for (const assignment of leadAssignments) {
      if (assignment.buyer?.profile && assignment.lead?.profile) {
        const buyerId = assignment.buyer.profile.id;
        const leadId = assignment.lead.profile.id;

        const existingLead = await prisma.curatedLeadAssignment.findFirst({
          where: { buyerProfileId: buyerId, leadProfileId: leadId },
        });

        if (!existingLead) {
          await prisma.curatedLeadAssignment.create({
            data: {
              buyerProfileId: buyerId,
              leadProfileId: leadId,
              status: 'PENDING',
            },
          });
          console.log(`Created curated lead assignment: ${assignment.buyer.name} -> ${assignment.lead.name}`);
        }
      }
    }

    console.log('Seeding operation completed successfully!');
    console.log(`Summary: ${insertedCount} profiles created, ${skippedCount} profiles skipped.`);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
